### PR TITLE
bump support PHP 8 & fos elastica 6 (only compatible Elasticsearch 7)

### LINKED ISSUE #185: Support for PHP 8.0
This plugin does not support PHP 8.0.
https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/blob/51a2b1edc280bfcfa6f206a98a38163a6500cd4a/composer.json#L8

### PR DESCRIPTION
**Pull request by wadjeroudi**
fix #185 

BC breaks: drop support PHP 7.3, fos elastica 6 needs elasticsearch 7.

### CODE REVIEW

**Review by er1z — APPROVED** [review]

**Comment by wadjeroudi** [comment]
the linked symfony 5.4 issue : https://github.com/Sylius/Sylius/issues/13342

will fix the fixtures.

**Comment by er1z** [comment]
For sure, I'm working for fixing some insights in terms of automatic tests, could you test if everything works fine?
https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/pull/187

**Comment by rimas-kudelis** [comment]
Hi, I just wanted to ping you guys on this. Is anything actually happening to get ES7 support in Sylius?

**Comment by jakubtobiasz** [comment]
Hi!
We've checked our `2.x` branch (tag: v2.0.0-beta1) and we have already ES7 there. Between this PR and our `2.x` branch there's nearly no difference. 

The only thing I can see to consider is PHP8 support which I think we should push by the separate PR. In my opinion merging this PR into `master` branch won't bring any added value.

**Comment by tgrochowski** [comment]
@wadjeroudi this PR will be closed and continued in https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/pull/194

**Pull request closed without merging**
