### PR TITLE
Sitewide search

### PR DESCRIPTION
**Pull request by mmenozzi**

### CODE REVIEW

**Comment by mmenozzi** [comment]
Hi guys,
this PR is still work in progress but if you can it would be great to have any kind of feedback.

**Comment by bitbager** [comment]
Hello there! Thank you for the PR. At this moment we are quite busy but I will do my best to have it merged as soon as it's ready. In the meantime, can I ask you to adjust the code to our BitBag standards? You will find more about them here: https://github.com/BitBagCommerce/BitBagBible. We use these standards in order to navigate through the code more intuitive. I also believe that there are la lot of point you can benefit from as a developer 🙂. Thank you in advance!

**Comment by mmenozzi** [comment]
> Hello there! Thank you for the PR. At this moment we are quite busy but I will do my best to have it merged as soon as it's ready. In the meantime, can I ask you to adjust the code to our BitBag standards? You will find more about them here: https://github.com/BitBagCommerce/BitBagBible. We use these standards in order to navigate through the code more intuitive. I also believe that there are la lot of points you can benefit from as a developer 🙂. Thank you in advance!

Yes I'll do my best.
Do you already noticed anything not compliant to your bible?

**Comment by bitbager** [comment]
As far as I have seen there were some small things missing like no final declaration, missing voids in specs and author headers. Overall the code seems to be high quality and meets our standards - it’s covered with specs & Behats, follows DI and good Symfony practices.

**Comment by mmenozzi** [comment]
Hi @bitbager, I think this PR is ready for review.
I've not documented anything yet because maybe something could change before it's merged.

**Comment by mmenozzi** [comment]
Hi @damonsson, I’ll open another another PR for the documentation.

**Comment by dzetah** [comment]
Thanks a lot for this feature @mmenozzi and @bitbager !

When will this be available under a tag ?

**Comment by bitbager** [comment]
Yes, it will. We need to test it properly first. If you want to have it earlier, feel free to switch to dev-master.

**Pull request merged**
