### PR TITLE
Update to elasticsearch 7

### PR DESCRIPTION
**Pull request by JakobTolkemit**

### CODE REVIEW

**Comment by damonsson** [comment]
Thank you @JakobTolkemit ! We'll check it ASAP.

**Comment by afasciaux** [comment]
Hi :)

Any chance to get ES7 support on master, and compatible sylius 1.8 ?

**Comment by damonsson** [comment]
This is one of our top priorities

**Comment by afasciaux** [comment]
@damonsson that's really great news, thanks !

Any chance to know when you think we can test it ?

**Comment by damonsson** [comment]
@afasciaux yes, we released 2.0.0-beta with ES7 support https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/tree/v2.0.0-beta1

**Pull request merged**
